实验练习：学习sklearn，实现kNN、决策树、贝叶斯算法对iris进行分类预测

# 鸢尾花数据集iris 介绍

鸢尾花数据集iris 是数据挖掘学习中最常用的数据集 http://archive.ics.uci.edu/ml/datasets/Iris

+ 鸢尾花数据集采集的是鸢尾花的测量数据以及其所属的类别，该数据集可用于**多分类问题**。
+ 测量数据包括:**萼片长度（sepal length）、萼片宽度（sepal width）、花瓣长度（petal length）、花瓣宽度（petal length）**。
+ 类别共分为三类:**Iris Setosa， Iris Versicolour，Iris Virginica**

# iris数据集查看

In [4]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_iris  #sklearn自带iris数据集 

+ 使用**sklearn.datasets.load_iris**即可加载相关数据集

In [6]:
iris = load_iris()    #查看dataset中的鸢尾花数据集  以dict形式存储
iris.keys()       # target==label

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [7]:
iris.target   #查看类标签列

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris.target_names  #查看类别名称

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [9]:
print(iris.DESCR)   # 查看数据集描述

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [10]:
iris.data    #查看数据列

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [11]:
iris.data.shape

(150, 4)

In [12]:
iris.feature_names   #查看属性名称

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# 利用kNN、决策树、贝叶斯算法对iris进行分类学习

## kNN

class  **sklearn.neighbors.KNeighborsClassifier**(n_neighbors=5, weights=’uniform’, algorithm=’auto’, leaf_size=30, p=2, metric=’minkowski’, metric_params=None, n_jobs=None, **kwargs) 

在sklearn库中，可以使用**sklearn.neighbors.KNeighborsClassifier** 创建一个K近邻分类器，主要参数有:
+ **n_neighbors**:用于指定分类器中K的大小(默认值为5，注意与 kmeans的区别)
+ **weights**:设置选中的K个点对分类结果影响的权重(默认值为平均 权重“uniform”，可以选择“distance”代表越近的点权重越高， 或者传入自己编写的以距离为参数的权重计算函数)
+ **algorithm**:设置用于计算临近点的方法，因为当数据量很大的情况下计算当前点和所有点的距离再选出最近的k各点，这个计算量是很 费时的，所以(选项中有ball_tree、kd_tree和brute，分别代表不 同的寻找邻居的优化算法，默认值为auto，根据训练数据自动选择)

In [13]:
# 给出萼片长度（sepal length）、萼片宽度（sepal width）、花瓣长度（petal length）、花瓣宽度（petal length）的值
#预测该鸢尾花是什么类型

from sklearn.datasets import load_iris
from sklearn import neighbors
from sklearn.model_selection import train_test_split
 
#查看iris数据集
iris = load_iris()

 
knn = neighbors.KNeighborsClassifier()    #实例化

Xtrain, Xtest, Ytrain, Ytest = train_test_split(iris.data, iris.target,test_size=0.3)  #划分训练集 和 测试集

knn.fit(Xtrain,Ytrain)    #训练数据集

score = knn.score(Xtest, Ytest)   #返回预测的准确度accuracy
score

0.9555555555555556

In [14]:
predict = knn.predict([[12,30,0.1,5]])   #预测
print(predict)

[0]


In [15]:
print(iris.target_names[predict])

['setosa']


## 决策树

在sklearn库中，可以使用**sklearn.tree.DecisionTreeClassifier**创 建一个决策树用于分类，其主要参数有:
+ **criterion** :用于选择属性的准则，可以传入“gini”代表基尼 系数，或者“entropy”代表信息增益。
+ **max_features** :表示在决策树结点进行分裂时，从多少个特征中选择最优特征。可以设定固定数目、百分比或其他标准。它的默认值是使用所有特征个数。

In [16]:
# 1. 导入需要的算法库 和 模块
from sklearn import tree
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score   #导入计算交叉验证值的函数cross_val_score
from sklearn.metrics import classification_report    #生成分类结果报告

In [28]:
#查看iris数据集
iris = load_iris()

Xtrain, Xtest, Ytrain, Ytest = train_test_split(iris.data, iris.target,test_size=0.3)  #划分训练集 和 测试集

clf = tree.DecisionTreeClassifier()    #实例化，默认gini系数
clf = clf.fit(Xtrain, Ytrain)

score = clf.score(Xtest, Ytest)   #返回预测的准确度accuracy
score

0.9333333333333333

In [29]:
cross_val_score(clf, iris.data, iris.target, cv=10)

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 0.93333333, 1.        , 1.        ])

这里我们将决策树分类器做为待评估的模型，iris.data鸢尾花数据做为特征， iris.target鸢尾花分类标签做为目标结果，通过设定cv为10，使用10折交叉验 证。得到最终的交叉验证得分。

In [30]:
clf.predict([[1,2,3,4]])

array([2])

In [31]:
print(iris.target_names[2])

virginica


In [21]:
# 画出决策树
import graphviz


feature_name = ['sepal length','sepal width','petal length','petal width']


dot_data = tree.export_graphviz(clf,feature_names= feature_name
                                ,class_names=["Iris-Setosa","Iris-Versicolour","Iris-Virginica"] 
                                ,filled=True,rounded=True,out_file = None)

graph = graphviz.Source(dot_data)
graph

ModuleNotFoundError: No module named 'graphviz'

In [22]:
clf_answer = clf.predict(Xtest)
print('\n\nThe classification report for DT:')
print(classification_report(Ytest, clf_answer))



The classification report for DT:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.91      0.95        11
           2       0.94      1.00      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



## 朴素贝叶斯

朴素贝叶斯分类器是一个以贝叶斯定理为基础的多分类的分类器。对于给定数据，首先基于特征的条件独立性假设，学习输入输出的联合概率分布，然后基于此模型，对给定的输入x，利用贝叶斯定理求出后验概率最大的输出y。

In [35]:
#导入包
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [36]:
#导入数据集
from sklearn import datasets
iris=datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [37]:
# 切分数据集
Xtrain, Xtest, ytrain, ytest = train_test_split(iris.data,
                                                iris.target,
                                                random_state=42)

In [38]:
#建模
clf = GaussianNB()      #实例化
clf.fit(Xtrain, ytrain)  #训练数据

GaussianNB(priors=None, var_smoothing=1e-09)

In [39]:
#在测试集上执行预测，proba导出的是每个样本属于某类的概率
clf.predict(Xtest)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [19]:
clf.predict_proba(Xtest)

array([[  5.97926853e-094,   9.95499546e-001,   4.50045384e-003],
       [  1.00000000e+000,   1.52146968e-013,   1.07136902e-020],
       [  1.71330808e-299,   6.04667826e-012,   1.00000000e+000],
       [  2.88508207e-096,   9.76485329e-001,   2.35146713e-002],
       [  1.36797133e-109,   8.51147229e-001,   1.48852771e-001],
       [  1.00000000e+000,   4.74962788e-013,   4.28854236e-021],
       [  3.25153316e-053,   9.99959350e-001,   4.06500520e-005],
       [  1.09216160e-176,   1.05015117e-006,   9.99998950e-001],
       [  3.27169186e-098,   9.93646597e-001,   6.35340277e-003],
       [  1.17401351e-060,   9.99944993e-001,   5.50073382e-005],
       [  1.00765817e-153,   5.02929583e-004,   9.99497070e-001],
       [  1.00000000e+000,   7.95517827e-017,   5.80301835e-025],
       [  1.00000000e+000,   1.83324108e-016,   2.96899989e-024],
       [  1.00000000e+000,   1.81709952e-016,   2.19054140e-024],
       [  1.00000000e+000,   2.58611124e-016,   6.24907433e-024],
       [  

In [10]:
#测试准确率
accuracy_score(ytest, clf.predict(Xtest))

NameError: name 'accuracy_score' is not defined

In [6]:
cross_val_score(clf, iris.data, iris.target, cv=10)

NameError: name 'cross_val_score' is not defined